### ISSUE TITLE
it doesn't sleep 1 second by default

### ISSUE THREAD

**Issue by x-yuri** [erikogan/wait4ports#3]
This lines takes no effect:

https://github.com/erikogan/wait4ports/blob/v0.3.1/main.c#L35

`sleep_seconds` are overridden in any case:

https://github.com/erikogan/wait4ports/blob/v0.3.1/main.c#L73

**Comment by x-yuri** [comment]
@erikogan It should either return `SLEEP_SECONDS` [here][1]. Initialization [here][2] is meaningless in any case. Well, that's the easiest way... The other one is to set `sleep_string` to string representation of `SLEEP_SECONDS` before [this line][3], and the latter shouldn't overwrite `sleep_seconds` unless the environment variable is nonempty.

[1]: https://github.com/erikogan/wait4ports/blob/v0.3.1/main.c#L98
[2]: https://github.com/erikogan/wait4ports/blob/v0.3.1/main.c#L35
[3]: https://github.com/erikogan/wait4ports/blob/v0.3.1/main.c#L39

**Comment by erikogan** [comment]
Sorry for the delay, I missed the emails on this issue somehow. 

Looking quickly, I believe you are correct. Returning `SLEEP_SECONDS` in `opt_atoi` won’t work, since it is also used for the timeout, but it could include a default value. 

I’ve just come back to working on a branch for 0.4.0 that makes a number of structural changes, but let me see if I can push 0.3.2 to fix this.

**Comment by erikogan** [comment]
I’ve released v0.3.2, which fixes this issue. Thanks for the feedback, and nice catch!

I’ve also added [an Alpine merge request](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16987) to include 0.3.2 in the base packages.

**Comment by x-yuri** [comment]
A little follow-up. Available since Alpine Linux 3.14.
